[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "onyx-client"
version = "1.0.0"
authors = [
  { name="Onyx Team", email="team@onyx.dev" },
]
description = "Official Python client for the Onyx Price Benchmarking & Scraper Engine"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx>=0.24.0",
]

[project.urls]
"Homepage" = "https://github.com/Tejas3479/onyx"
"Bug Tracker" = "https://github.com/Tejas3479/onyx/issues"
