"""baseline

Revision ID: 15109c95aff3
Revises: 
Create Date: 2026-08-14 19:53:39.323923

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15109c95aff3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('batchjob',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_urls', sa.Integer(), nullable=False),
    sa.Column('processed_urls', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('export_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawljob',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('render_js', sa.Boolean(), nullable=False),
    sa.Column('output_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('destinations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departmentpurchaserecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_item_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity_purchased', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_document', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destination',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gemlppcache',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_matched', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gem_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('catalog_price', sa.Float(), nullable=True),
    sa.Column('lpp_price', sa.Float(), nullable=True),
    sa.Column('source_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nonstandardestimate',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comparable_items', sa.JSON(), nullable=True),
    sa.Column('estimated_price', sa.Float(), nullable=True),
    sa.Column('price_range_low', sa.Float(), nullable=True),
    sa.Column('price_range_high', sa.Float(), nullable=True),
    sa.Column('confidence_rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spec_match_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifiedrate',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contract_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricealert',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricehistory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('screenshot_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priceresult',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_includes_gst', sa.Boolean(), nullable=True),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('availability', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('screenshot_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricesearch',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sources_checked', sa.Integer(), nullable=False),
    sa.Column('results_found', sa.Integer(), nullable=False),
    sa.Column('resolved_tier', sa.Integer(), nullable=True),
    sa.Column('tier_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier_skip_reasons', sa.JSON(), nullable=True),
    sa.Column('query_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('report',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signatory_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduledcrawl',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('scheduledcrawl')
    op.drop_table('report')
    op.drop_table('proxy')
    op.drop_table('pricesearch')
    op.drop_table('priceresult')
    op.drop_table('pricehistory')
    op.drop_table('pricealert')
    op.drop_table('notifiedrate')
    op.drop_table('nonstandardestimate')
    op.drop_table('gemlppcache')
    op.drop_table('destination')
    op.drop_table('departmentpurchaserecord')
    op.drop_table('crawljob')
    op.drop_table('batchjob')
    op.drop_table('apikey')
    # ### end Alembic commands ###
